name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run tests
        run: |
          echo "Running tests..."
          # Add your actual test command here, e.g., pnpm test

  deploy:
    if: github.event_name == 'push'
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Pull latest code for production or staging
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "Deploying to production"
            git pull origin main
            working_dir="/var/www/thebff-main"
            pm2_server="thebff-production"
          else
            echo "Deploying to staging"
            git pull origin dev
            working_dir="/var/www/thebff-dev"
            pm2_server="thebff-staging"
          fi
        working-directory: ${{ working_dir }}

      - name: Cache server dependencies and Next.js build cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ working_dir }}/node_modules
            /root/.pnpm-store
            ${{ working_dir }}/.next/cache
          key: ${{ runner.os }}-pnpm-nextjs-${{ hashFiles('${{ working_dir }}/pnpm-lock.yaml') }}-${{ hashFiles('${{ working_dir }}/**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-nextjs-${{ hashFiles('${{ working_dir }}/pnpm-lock.yaml') }}-
            
      - name: Install server dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ${{ working_dir }}

      - name: Build application
        run: pnpm build
        working-directory: ${{ working_dir }}

      - name: Restart server
        run: pm2 restart "${{ pm2_server }}"
        working-directory: ${{ working_dir }}
